# Generated by Django 5.0.6 on 2024-07-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_is_cancelled_mymodel_is_canceled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
