# Generated by Django 5.0.6 on 2024-07-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
