# Generated by Django 5.0.6 on 2024-07-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_cancel_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cancel_appointment',
        ),
    ]
